# Generated by Django 6.0.5 on 2026-06-01 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="warehouse name"),
                ),
                ("location", models.CharField(max_length=255, verbose_name="location")),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warehouses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "warehouse",
                "verbose_name_plural": "warehouses",
            },
        ),
        migrations.CreateModel(
            name="StockItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_id", models.PositiveIntegerField(verbose_name="book id")),
                (
                    "sku",
                    models.CharField(max_length=100, unique=True, verbose_name="sku"),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=0, verbose_name="quantity"),
                ),
                (
                    "reserved_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="reserved quantity"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_items",
                        to="warehouse.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "stock item",
                "verbose_name_plural": "stock items",
                "indexes": [
                    models.Index(
                        fields=["book_id"], name="warehouse_s_book_id_bd0429_idx"
                    ),
                    models.Index(fields=["sku"], name="warehouse_s_sku_40120f_idx"),
                ],
            },
        ),
    ]
